/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { H5PCreateInput } from "./H5PCreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateH5PArgs {
  @ApiProperty({
    required: true,
    type: () => H5PCreateInput,
  })
  @ValidateNested()
  @Type(() => H5PCreateInput)
  @Field(() => H5PCreateInput, { nullable: false })
  data!: H5PCreateInput;
}

export { CreateH5PArgs as CreateH5PArgs };
