/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { H5PWhereInput } from "./H5PWhereInput";
import { Type } from "class-transformer";

@ArgsType()
class H5PCountArgs {
  @ApiProperty({
    required: false,
    type: () => H5PWhereInput,
  })
  @Field(() => H5PWhereInput, { nullable: true })
  @Type(() => H5PWhereInput)
  where?: H5PWhereInput;
}

export { H5PCountArgs as H5PCountArgs };
