/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { H5PWhereUniqueInput } from "./H5PWhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { H5PUpdateInput } from "./H5PUpdateInput";

@ArgsType()
class UpdateH5PArgs {
  @ApiProperty({
    required: true,
    type: () => H5PWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => H5PWhereUniqueInput)
  @Field(() => H5PWhereUniqueInput, { nullable: false })
  where!: H5PWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => H5PUpdateInput,
  })
  @ValidateNested()
  @Type(() => H5PUpdateInput)
  @Field(() => H5PUpdateInput, { nullable: false })
  data!: H5PUpdateInput;
}

export { UpdateH5PArgs as UpdateH5PArgs };
