/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LearningMapService } from "../learningMap.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LearningMapCreateInput } from "./LearningMapCreateInput";
import { LearningMap } from "./LearningMap";
import { LearningMapFindManyArgs } from "./LearningMapFindManyArgs";
import { LearningMapWhereUniqueInput } from "./LearningMapWhereUniqueInput";
import { LearningMapUpdateInput } from "./LearningMapUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LearningMapControllerBase {
  constructor(
    protected readonly service: LearningMapService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LearningMap })
  @nestAccessControl.UseRoles({
    resource: "LearningMap",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLearningMap(
    @common.Body() data: LearningMapCreateInput
  ): Promise<LearningMap> {
    return await this.service.createLearningMap({
      data: data,
      select: {
        accessibility: true,
        createdAt: true,
        description: true,
        discipline: true,
        id: true,
        language: true,
        learningOutcomes: true,
        owner: true,
        subject: true,
        title: true,
        topic: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [LearningMap] })
  @ApiNestedQuery(LearningMapFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LearningMap",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async learningMaps(@common.Req() request: Request): Promise<LearningMap[]> {
    const args = plainToClass(LearningMapFindManyArgs, request.query);
    return this.service.learningMaps({
      ...args,
      select: {
        accessibility: true,
        createdAt: true,
        description: true,
        discipline: true,
        id: true,
        language: true,
        learningOutcomes: true,
        owner: true,
        subject: true,
        title: true,
        topic: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LearningMap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LearningMap",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async learningMap(
    @common.Param() params: LearningMapWhereUniqueInput
  ): Promise<LearningMap | null> {
    const result = await this.service.learningMap({
      where: params,
      select: {
        accessibility: true,
        createdAt: true,
        description: true,
        discipline: true,
        id: true,
        language: true,
        learningOutcomes: true,
        owner: true,
        subject: true,
        title: true,
        topic: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LearningMap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LearningMap",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLearningMap(
    @common.Param() params: LearningMapWhereUniqueInput,
    @common.Body() data: LearningMapUpdateInput
  ): Promise<LearningMap | null> {
    try {
      return await this.service.updateLearningMap({
        where: params,
        data: data,
        select: {
          accessibility: true,
          createdAt: true,
          description: true,
          discipline: true,
          id: true,
          language: true,
          learningOutcomes: true,
          owner: true,
          subject: true,
          title: true,
          topic: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LearningMap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LearningMap",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLearningMap(
    @common.Param() params: LearningMapWhereUniqueInput
  ): Promise<LearningMap | null> {
    try {
      return await this.service.deleteLearningMap({
        where: params,
        select: {
          accessibility: true,
          createdAt: true,
          description: true,
          discipline: true,
          id: true,
          language: true,
          learningOutcomes: true,
          owner: true,
          subject: true,
          title: true,
          topic: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
